import {
  AppSettings,
  CurriculumEntry,
  LessonLogEntry,
  SubjectAlias,
  TeacherProfile,
  TimetableSlot,
} from '../types';

export const INITIAL_PROFILE: TeacherProfile = {
  teacherName: 'Nguyễn Văn Sang',
  school: 'Trường Cao đẳng nghề 1-BQP',
  department: 'Tổ Toán - Tin',
  reviewer: 'Trần Thị Bích Thảo',
  reviewerTitle: 'Tổ trưởng chuyên môn',
  schoolYear: '2026 - 2027',
  semester: 'Học kỳ I',
};

export const INITIAL_SETTINGS: AppSettings = {
  schoolYear: '2026 - 2027',
  currentWeek: 1,
  startMondayDate: '2026-09-07', // Năm học 2026-2027 bắt đầu từ thứ Hai 07/09/2026
  includeSaturday: false,
  morningPeriods: 5,
  afternoonPeriods: 5,
  autoMatchPPCT: true,
};

export const INITIAL_ALIASES: SubjectAlias[] = [
  { id: 'al-1', alias: 'ĐS', canonicalSubject: 'Toán', grade: 10 },
  { id: 'al-2', alias: 'Đại số', canonicalSubject: 'Toán', grade: 10 },
  { id: 'al-3', alias: 'GT', canonicalSubject: 'Toán', grade: 12 },
  { id: 'al-4', alias: 'Giải tích', canonicalSubject: 'Toán', grade: 12 },
  { id: 'al-5', alias: 'HH', canonicalSubject: 'Toán' },
  { id: 'al-6', alias: 'Hình học', canonicalSubject: 'Toán' },
  { id: 'al-7', alias: 'Ôn Toán', canonicalSubject: 'Toán' },
  { id: 'al-8', alias: 'HĐTN', canonicalSubject: 'HĐTN-HN' },
];

export const INITIAL_CURRICULUM: CurriculumEntry[] = [
  // Toán Khối 10 - Học kỳ I
  {
    id: 'ppct-10-1',
    subject: 'Toán',
    grade: 10,
    periodNumber: 1,
    lessonTitle: 'Bài 1: Mệnh đề',
    semester: 'Học kỳ I',
    category: 'Đại số',
    note: 'Lý thuyết cơ bản',
  },
  {
    id: 'ppct-10-2',
    subject: 'Toán',
    grade: 10,
    periodNumber: 2,
    lessonTitle: 'Bài 1: Mệnh đề',
    semester: 'Học kỳ I',
    category: 'Đại số',
    note: 'Mệnh đề chứa biến, phủ định',
  },
  {
    id: 'ppct-10-3',
    subject: 'Toán',
    grade: 10,
    periodNumber: 3,
    lessonTitle: 'Bài 2: Tập hợp và các phép toán trên tập hợp',
    semester: 'Học kỳ I',
    category: 'Đại số',
  },
  {
    id: 'ppct-10-4',
    subject: 'Toán',
    grade: 10,
    periodNumber: 4,
    lessonTitle: 'Bài 2: Tập hợp và các phép toán trên tập hợp',
    semester: 'Học kỳ I',
    category: 'Đại số',
  },
  {
    id: 'ppct-10-5',
    subject: 'Toán',
    grade: 10,
    periodNumber: 5,
    lessonTitle: 'Bài tập: Mệnh đề và Tập hợp',
    semester: 'Học kỳ I',
    category: 'Đại số',
    note: 'Luyện tập củng cố',
  },
  {
    id: 'ppct-10-6',
    subject: 'Toán',
    grade: 10,
    periodNumber: 6,
    lessonTitle: 'Bài 3: Giá trị lượng giác của một góc từ 0° đến 180°',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-10-7',
    subject: 'Toán',
    grade: 10,
    periodNumber: 7,
    lessonTitle: 'Bài 3: Giá trị lượng giác của một góc từ 0° đến 180°',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-10-8',
    subject: 'Toán',
    grade: 10,
    periodNumber: 8,
    lessonTitle: 'Bài 4: Hệ thức lượng trong tam giác',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-10-9',
    subject: 'Toán',
    grade: 10,
    periodNumber: 9,
    lessonTitle: 'Bài 4: Hệ thức lượng trong tam giác',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-10-10',
    subject: 'Toán',
    grade: 10,
    periodNumber: 10,
    lessonTitle: 'Kiểm tra thường xuyên 15 phút & Luyện tập hệ thức lượng',
    semester: 'Học kỳ I',
    category: 'Kiểm tra',
  },

  // Toán Khối 12 - Học kỳ I
  {
    id: 'ppct-12-1',
    subject: 'Toán',
    grade: 12,
    periodNumber: 1,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },
  {
    id: 'ppct-12-2',
    subject: 'Toán',
    grade: 12,
    periodNumber: 2,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },
  {
    id: 'ppct-12-3',
    subject: 'Toán',
    grade: 12,
    periodNumber: 3,
    lessonTitle: 'Bài 2: Cực trị của hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },
  {
    id: 'ppct-12-4',
    subject: 'Toán',
    grade: 12,
    periodNumber: 4,
    lessonTitle: 'Bài 2: Cực trị của hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },
  {
    id: 'ppct-12-5',
    subject: 'Toán',
    grade: 12,
    periodNumber: 5,
    lessonTitle: 'Bài 1: Vectơ và các phép toán trong không gian',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-12-6',
    subject: 'Toán',
    grade: 12,
    periodNumber: 6,
    lessonTitle: 'Bài 1: Vectơ và các phép toán trong không gian',
    semester: 'Học kỳ I',
    category: 'Hình học',
  },
  {
    id: 'ppct-12-7',
    subject: 'Toán',
    grade: 12,
    periodNumber: 7,
    lessonTitle: 'Luyện tập: Tính đơn điệu và cực trị hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },
  {
    id: 'ppct-12-8',
    subject: 'Toán',
    grade: 12,
    periodNumber: 8,
    lessonTitle: 'Bài 3: Giá trị lớn nhất và nhỏ nhất của hàm số',
    semester: 'Học kỳ I',
    category: 'Giải tích',
  },

  // Hoạt động trải nghiệm, hướng nghiệp Khối 10
  {
    id: 'ppct-hdtn-1',
    subject: 'HĐTN-HN',
    grade: 10,
    periodNumber: 1,
    lessonTitle: 'Chủ đề 1: Phát huy truyền thống nhà trường',
    semester: 'Học kỳ I',
    category: 'Chủ đề',
  },
  {
    id: 'ppct-hdtn-2',
    subject: 'HĐTN-HN',
    grade: 10,
    periodNumber: 2,
    lessonTitle: 'Chủ đề 1: Phát huy truyền thống nhà trường',
    semester: 'Học kỳ I',
    category: 'Chủ đề',
  },
  {
    id: 'ppct-hdtn-3',
    subject: 'HĐTN-HN',
    grade: 10,
    periodNumber: 3,
    lessonTitle: 'Chủ đề 2: Khám phá bản thân và môi trường học tập',
    semester: 'Học kỳ I',
    category: 'Chủ đề',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // TUẦN 1:
  // Thứ 2 (2)
  {
    id: 'tkb-w1-2-m-1',
    weekNumber: 1,
    year: 2024,
    weekday: 2,
    session: 'morning',
    period: 1,
    rawText: 'Chào cờ',
    className: '',
    subject: '',
    activity: 'Chào cờ',
  },
  {
    id: 'tkb-w1-2-m-2',
    weekNumber: 1,
    year: 2024,
    weekday: 2,
    session: 'morning',
    period: 2,
    rawText: '10A8-HĐTN-HN',
    className: '10A8',
    subject: 'HĐTN-HN',
  },
  {
    id: 'tkb-w1-2-m-3',
    weekNumber: 1,
    year: 2024,
    weekday: 2,
    session: 'morning',
    period: 3,
    rawText: '10A8-Toán',
    className: '10A8',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-2-m-4',
    weekNumber: 1,
    year: 2024,
    weekday: 2,
    session: 'morning',
    period: 4,
    rawText: '10A8-Toán',
    className: '10A8',
    subject: 'Toán',
  },

  // Thứ 3 (3)
  {
    id: 'tkb-w1-3-m-1',
    weekNumber: 1,
    year: 2024,
    weekday: 3,
    session: 'morning',
    period: 1,
    rawText: '12B1-Toán',
    className: '12B1',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-3-m-2',
    weekNumber: 1,
    year: 2024,
    weekday: 3,
    session: 'morning',
    period: 2,
    rawText: '12B1-Toán',
    className: '12B1',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-3-m-3',
    weekNumber: 1,
    year: 2024,
    weekday: 3,
    session: 'morning',
    period: 3,
    rawText: '12B6-Toán',
    className: '12B6',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-3-m-4',
    weekNumber: 1,
    year: 2024,
    weekday: 3,
    session: 'morning',
    period: 4,
    rawText: '12B6-Toán',
    className: '12B6',
    subject: 'Toán',
  },

  // Thứ 4 (4)
  {
    id: 'tkb-w1-4-m-2',
    weekNumber: 1,
    year: 2024,
    weekday: 4,
    session: 'morning',
    period: 2,
    rawText: '10A11-Toán',
    className: '10A11',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-4-m-3',
    weekNumber: 1,
    year: 2024,
    weekday: 4,
    session: 'morning',
    period: 3,
    rawText: '10A11-Toán',
    className: '10A11',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-4-a-1',
    weekNumber: 1,
    year: 2024,
    weekday: 4,
    session: 'afternoon',
    period: 1,
    rawText: '10A8-Ôn Toán',
    className: '10A8',
    subject: 'Ôn Toán',
  },
  {
    id: 'tkb-w1-4-a-2',
    weekNumber: 1,
    year: 2024,
    weekday: 4,
    session: 'afternoon',
    period: 2,
    rawText: '10A8-Ôn Toán',
    className: '10A8',
    subject: 'Ôn Toán',
  },

  // Thứ 5 (5)
  {
    id: 'tkb-w1-5-m-1',
    weekNumber: 1,
    year: 2024,
    weekday: 5,
    session: 'morning',
    period: 1,
    rawText: '12B1-Toán',
    className: '12B1',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-5-m-2',
    weekNumber: 1,
    year: 2024,
    weekday: 5,
    session: 'morning',
    period: 2,
    rawText: '12B1-Toán',
    className: '12B1',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-5-m-4',
    weekNumber: 1,
    year: 2024,
    weekday: 5,
    session: 'morning',
    period: 4,
    rawText: '10A8-Toán',
    className: '10A8',
    subject: 'Toán',
  },

  // Thứ 6 (6)
  {
    id: 'tkb-w1-6-m-1',
    weekNumber: 1,
    year: 2024,
    weekday: 6,
    session: 'morning',
    period: 1,
    rawText: '12B6-Toán',
    className: '12B6',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-6-m-2',
    weekNumber: 1,
    year: 2024,
    weekday: 6,
    session: 'morning',
    period: 2,
    rawText: '10A11-Toán',
    className: '10A11',
    subject: 'Toán',
  },
  {
    id: 'tkb-w1-6-m-5',
    weekNumber: 1,
    year: 2024,
    weekday: 6,
    session: 'morning',
    period: 5,
    rawText: 'Sinh hoạt lớp',
    className: '10A8',
    subject: '',
    activity: 'Sinh hoạt lớp',
  },
];

export const INITIAL_LESSON_LOGS: LessonLogEntry[] = [
  {
    id: 'log-w1-1',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-02',
    weekday: 2,
    session: 'morning',
    period: 1,
    subject: 'Chào cờ',
    className: 'Toàn trường',
    curriculumPeriod: undefined,
    lessonTitle: 'Chào cờ đầu tuần & Khai giảng năm học mới',
    adjustment: 'Chào cờ tập trung',
    status: 'taught',
    isManuallyEdited: false,
    activity: 'Chào cờ',
    timetableSlotId: 'tkb-w1-2-m-1',
  },
  {
    id: 'log-w1-2',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-02',
    weekday: 2,
    session: 'morning',
    period: 2,
    subject: 'HĐTN-HN',
    className: '10A8',
    curriculumPeriod: 1,
    lessonTitle: 'Chủ đề 1: Phát huy truyền thống nhà trường',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-2-m-2',
  },
  {
    id: 'log-w1-3',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-02',
    weekday: 2,
    session: 'morning',
    period: 3,
    subject: 'Toán',
    className: '10A8',
    curriculumPeriod: 1,
    lessonTitle: 'Bài 1: Mệnh đề',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-2-m-3',
  },
  {
    id: 'log-w1-4',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-02',
    weekday: 2,
    session: 'morning',
    period: 4,
    subject: 'Toán',
    className: '10A8',
    curriculumPeriod: 2,
    lessonTitle: 'Bài 1: Mệnh đề',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-2-m-4',
  },
  {
    id: 'log-w1-5',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-03',
    weekday: 3,
    session: 'morning',
    period: 1,
    subject: 'Toán',
    className: '12B1',
    curriculumPeriod: 1,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-3-m-1',
  },
  {
    id: 'log-w1-6',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-03',
    weekday: 3,
    session: 'morning',
    period: 2,
    subject: 'Toán',
    className: '12B1',
    curriculumPeriod: 2,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-3-m-2',
  },
  {
    id: 'log-w1-7',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-03',
    weekday: 3,
    session: 'morning',
    period: 3,
    subject: 'Toán',
    className: '12B6',
    curriculumPeriod: 1,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    adjustment: '',
    status: 'taught',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-3-m-3',
  },
  {
    id: 'log-w1-8',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-03',
    weekday: 3,
    session: 'morning',
    period: 4,
    subject: 'Toán',
    className: '12B6',
    curriculumPeriod: 2,
    lessonTitle: 'Bài 1: Tính đơn điệu của hàm số',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-3-m-4',
  },
  {
    id: 'log-w1-9',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-04',
    weekday: 4,
    session: 'morning',
    period: 2,
    subject: 'Toán',
    className: '10A11',
    curriculumPeriod: 1,
    lessonTitle: 'Bài 1: Mệnh đề',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-4-m-2',
  },
  {
    id: 'log-w1-10',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-04',
    weekday: 4,
    session: 'morning',
    period: 3,
    subject: 'Toán',
    className: '10A11',
    curriculumPeriod: 2,
    lessonTitle: 'Bài 1: Mệnh đề',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-4-m-3',
  },
  {
    id: 'log-w1-11',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-04',
    weekday: 4,
    session: 'afternoon',
    period: 1,
    subject: 'Ôn Toán',
    className: '10A8',
    curriculumPeriod: undefined,
    lessonTitle: 'Luyện tập phương pháp giải toán mệnh đề',
    adjustment: 'Dạy tăng cường theo kế hoạch tổ',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-4-a-1',
  },
  {
    id: 'log-w1-12',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-04',
    weekday: 4,
    session: 'afternoon',
    period: 2,
    subject: 'Ôn Toán',
    className: '10A8',
    curriculumPeriod: undefined,
    lessonTitle: 'Rèn luyện kĩ năng chứng minh phản chứng',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-4-a-2',
  },
  {
    id: 'log-w1-13',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-05',
    weekday: 5,
    session: 'morning',
    period: 1,
    subject: 'Toán',
    className: '12B1',
    curriculumPeriod: 3,
    lessonTitle: 'Bài 2: Cực trị của hàm số',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-5-m-1',
  },
  {
    id: 'log-w1-14',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-05',
    weekday: 5,
    session: 'morning',
    period: 2,
    subject: 'Toán',
    className: '12B1',
    curriculumPeriod: 4,
    lessonTitle: 'Bài 2: Cực trị của hàm số',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-5-m-2',
  },
  {
    id: 'log-w1-15',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-05',
    weekday: 5,
    session: 'morning',
    period: 4,
    subject: 'Toán',
    className: '10A8',
    curriculumPeriod: 3,
    lessonTitle: 'Bài 2: Tập hợp và các phép toán trên tập hợp',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-5-m-4',
  },
  {
    id: 'log-w1-16',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-06',
    weekday: 6,
    session: 'morning',
    period: 1,
    subject: 'Toán',
    className: '12B6',
    curriculumPeriod: 3,
    lessonTitle: 'Bài 2: Cực trị của hàm số',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-6-m-1',
  },
  {
    id: 'log-w1-17',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-06',
    weekday: 6,
    session: 'morning',
    period: 2,
    subject: 'Toán',
    className: '10A11',
    curriculumPeriod: 3,
    lessonTitle: 'Bài 2: Tập hợp và các phép toán trên tập hợp',
    adjustment: '',
    status: 'pending',
    isManuallyEdited: false,
    timetableSlotId: 'tkb-w1-6-m-2',
  },
  {
    id: 'log-w1-18',
    weekNumber: 1,
    year: 2024,
    date: '2024-09-06',
    weekday: 6,
    session: 'morning',
    period: 5,
    subject: 'Sinh hoạt lớp',
    className: '10A8',
    curriculumPeriod: undefined,
    lessonTitle: 'Sinh hoạt chủ nhiệm: Ổn định nề nếp tuần 1',
    adjustment: 'GVCN thực hiện',
    status: 'pending',
    isManuallyEdited: false,
    activity: 'Sinh hoạt lớp',
    timetableSlotId: 'tkb-w1-6-m-5',
  },
];
